source 'https://rubygems.org'
gem 'sinatra', '~>2.0.0'
gem 'sinatra-simple-navigation', '~>4.1.0'
gem 'sinatra-static-assets', '~>1.0.4'
gem 'dragonfly', '~>1.0.3'
gem 'kramdown', '~>1.7.0'
gem 'addressable'
gem 'puma', '~>3.4.0'
gem 'aws-sdk'

group :development do
	gem 'pry'
  gem 'rspec'
  gem 'rack-test'
  gem 'rdoc'
  gem 'bundler'
  gem 'simplecov'
  gem 'simplecov-rcov'
  gem 'shotgun'
end
